### PR TITLE
support: yarn support + cache[clear, get, has]

### PR DESCRIPTION
**Pull request by krishpranav**
hey nuke

added caching functions 

great references: https://developer.mozilla.org/en-US/docs/Web/API/Cache, https://stackoverflow.com/questions/14266730/js-how-to-cache-a-variable

### CODE REVIEW

**Comment by NukeWilliams** [comment]
let me just review it

**Comment by krishpranav** [comment]
ok sure take your own time

**Review by NukeWilliams — CHANGES_REQUESTED** [review]
caching is great clear, has, delete functions are good. but the thing is the get function it returns the key as false it is wrong it will let the app crashing or produces a bug. so change the return from false to anything like undefined?

**Comment by krishpranav** [comment]
oops i forget about it. the get methods should returns undefined let me just change it

**Comment by krishpranav** [comment]
fixed @NukeWilliams

**Review by NukeWilliams — APPROVED** [review]
GOOD

**Comment by NukeWilliams** [comment]
lets wait for @Abhimishra2424 to review the changes you've done

**Comment by krishpranav** [comment]
ok sure

**Comment by Abhimishra2424** [comment]
> lets wait for @Abhimishra2424 to review the changes you've done

i check it

**Comment by NukeWilliams** [comment]
> > lets wait for @Abhimishra2424 to review the changes you've done
> 
> i check it

yea sure waiting for your review @Abhimishra2424

**Comment by krishpranav** [comment]
@NukeWilliams can you create a discord server and add all of us in it. it would be great for discussion, new pull request notifcations?

**Comment by NukeWilliams** [comment]
will do it @krishpranav

**Comment by krishpranav** [comment]
great

**Comment by Abhimishra2424** [comment]
plz send the link discord server

**Comment by NukeWilliams** [comment]
yea sure

**Review by Abhimishra2424 — APPROVED** [review]

**Comment by NukeWilliams** [comment]
discord link: 
https://discord.gg/MPVRz6Rp

**Comment by krishpranav** [comment]
joined

**Pull request merged**
